In [1]:
import numpy as np 
import pandas as pd 
import sys
sys.path.append('/home/ak/Documents/Research/hsmm/')

from IPython.display import Markdown
import datetime as dt 
from hsmm_core.data_utils import get_files_for_ticker, load_data
ticker = 'AAL'
import os

# Downloading data

In [2]:
Markdown(""" **The function that loads data is still called load_data. The basic arguments 
to this function is the name of the ticker (that corresponds to the sub folder locally on disk)
and optionally dates by which i can filter the loaded data.**
""")

 **The function that loads data is still called load_data. The basic arguments 
to this function is the name of the ticker (that corresponds to the sub folder locally on disk)
and optionally dates by which i can filter the loaded data.**


In [3]:
Markdown(""" **Calling it with simply the ticker name will return all dates available for the 
ticker**""")

 **Calling it with simply the ticker name will return all dates available for the 
ticker**

In [4]:
data1 = load_data(ticker) 

In [5]:
data1.keys() #function produces dictionaries

['20170125',
 '20170124',
 '20170127',
 '20170126',
 '20170120',
 '20170123',
 '20180412',
 '20180413',
 '20180410',
 '20180411',
 '20180416',
 '20180417',
 '20180418',
 '20180219',
 '20180419',
 '20180202',
 '20170118',
 '20180212',
 '20180213',
 '20180214',
 '20180215',
 '20180216',
 '20170130',
 '20170131',
 '20180409',
 '20170119',
 '20170117',
 '20180405',
 '20180404',
 '20170116',
 '20180406',
 '20180403',
 '20180221',
 '20180220',
 '20180209',
 '20180208',
 '20180227',
 '20180226',
 '20180228',
 '20180201',
 '20180207',
 '20180206',
 '20180205',
 '20180223',
 '20180420',
 '20180222']

In [6]:
Markdown(""" **If a given date range is required, that can be passed as arguments to the 
loading function. Dates can be passed as datetime objects or strings in format YYYYMMDD**""")

 **If a given date range is required, that can be passed as arguments to the 
loading function. Dates can be passed as datetime objects or strings in format YYYYMMDD**

In [7]:
?load_data

In [8]:
start = '20180220' 
end  = '20180418' 
data2 = load_data(ticker, start_date=start, end_date=end)


In [9]:
Markdown(""" **When labelling data, the labeller has two levels of 
configuration, the first mandatory and the second optional and contigent 
on the selections of the first level. At the first level one needs to 
choose:** 

- **labelling_method**: How do i compare the current row 
to upcoming rows to decide whether it should be labelled as an up move
down move or nothing. One can choose to compare the start and end point 
of an interval / the start point to all points in an interval / the 
start point to an average value in an interval. Moreover at this stage we make a choice of 
whether we want to use absolute level of comparison. This will be apparent by the name 
of the labelling method as it will have one of the suffixes: '_abs'/ '_pct'.  

- **thrshd_method:** How to calculate the % level that 
constitutes an up move (down move). One can choose to use an arbitrary 
level (hard coded) or to calculate an adaptive level based on historical
vol.
""")

 **When labelling data, the labeller has two levels of 
configuration, the first mandatory and the second optional and contigent 
on the selections of the first level. At the first level one needs to 
choose:** 

- **labelling_method**: How do i compare the current row 
to upcoming rows to decide whether it should be labelled as an up move
down move or nothing. One can choose to compare the start and end point 
of an interval / the start point to all points in an interval / the 
start point to an average value in an interval. Moreover at this stage we make a choice of 
whether we want to use absolute level of comparison. This will be apparent by the name 
of the labelling method as it will have one of the suffixes: '_abs'/ '_pct'.  

- **thrshd_method:** How to calculate the % level that 
constitutes an up move (down move). One can choose to use an arbitrary 
level (hard coded) or to calculate an adaptive level based on historical
vol.


In [10]:
Markdown(""" **If one chooses to threshold up/down moves by some method 
that depends on historical vol, a second level of configuration 
is required that will set the following variables:**

- **thrshd_vol_window:** How many days to use too calculate the a
average used for historical vol. 

- **updown_thrshd_vol_pct:** What perecent of the historical vol consitutes 
an up move/down move""")

 **If one chooses to threshold up/down moves by some method 
that depends on historical vol, a second level of configuration 
is required that will set the following variables:**

- **thrshd_vol_window:** How many days to use too calculate the a
average used for historical vol. 

- **updown_thrshd_vol_pct:** What perecent of the historical vol consitutes 
an up move/down move

In [11]:
Markdown(""" **Let us create an working example. We 'd like to 
label points as:** 

- Compare the start and end point of an interval including 10 trades
 **<-- labelling window is 10 and our labelling method is simple_ep.** 

-Set the absolute level of up or down move as the 10% of averaged historical vol of 
last 5 days (simple average) **<-- thrshd_method is historical_vol_ma, updown_thrshd_vol_pct 
is 10, thrshd_vol_window is 5.**
""")

 **Let us create an working example. We 'd like to 
label points as:** 

- Compare the start and end point of an interval including 10 trades
 **<-- labelling window is 10 and our labelling method is simple_ep.** 

-Set the absolute level of up or down move as the 10% of averaged historical vol of 
last 5 days (simple average) **<-- thrshd_method is historical_vol_ma, updown_thrshd_vol_pct 
is 10, thrshd_vol_window is 5.**


In [12]:
from hsmm_core.consts import LabellingChoice, ThresholdMethod 
from hsmm_core.labelling import DataLabellingSimple 


labeller = DataLabellingSimple(
                    # Style of labelling method - Here we compare rolling 
                    # intervals end points in absolute terms 
                    labelling_method=LabellingChoice.simple_ep_abs, 
                    # Window for labelling method= Number of look ahead trades that control up /down move
                    rolling_window=5,
                    # Calculate threshold by means of moving average historical vol
                    thrshd_method=ThresholdMethod.historical_vol_ma,
                    # Use the last 5 days for the above average. 
                    thrshd_vol_window=5,
                    # Pct of historical vol to use for threshold, i.e. 0.1 * historical vol
                    updown_thrshd_vol_pct=10.)


In [13]:
labeller.label_training_data(data1)  

/home/ak/virtualenvs/DataAnalysis/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/ak/virtualenvs/DataAnalysis/local/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/ak/Documents/Research/hsmm/hsmm_core/labelling.py:280: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  apply(lambda row: self.label_func_(row, effective_threshold))[::-1]


In [14]:
labeller.__dict__['available_dates_for_ticker_']['AAL']

['20170116',
 '20170117',
 '20170118',
 '20170119',
 '20170120',
 '20170123',
 '20170124',
 '20170125',
 '20170126',
 '20170127',
 '20170130',
 '20170131',
 '20180201',
 '20180202',
 '20180205',
 '20180206',
 '20180207',
 '20180208',
 '20180209',
 '20180212',
 '20180213',
 '20180214',
 '20180215',
 '20180216',
 '20180219',
 '20180220',
 '20180221',
 '20180222',
 '20180223',
 '20180226',
 '20180227',
 '20180228',
 '20180403',
 '20180404',
 '20180405',
 '20180406',
 '20180409',
 '20180410',
 '20180411',
 '20180412',
 '20180413',
 '20180416',
 '20180417',
 '20180418',
 '20180419',
 '20180420']

In [15]:
 Markdown(""" **Here is another example, where we dont use the historical vol at all. Instead 
we set an arbitrary level as a pct of price change (notice how this is reflected to 
the name of hte labelling method). We still just compare the end points of 
a rolling interval. Here we use 1 %**""") 

 **Here is another example, where we dont use the historical vol at all. Instead 
we set an arbitrary level as a pct of price change (notice how this is reflected to 
the name of hte labelling method). We still just compare the end points of 
a rolling interval. Here we use 1 %**

In [50]:
labeller = DataLabellingSimple(
                    # Style of labelling method - Here we compare rolling 
                    # inervals end points in absolute terms 
                    labelling_method=LabellingChoice.simple_ep_abs, 
                    # Window for labelling method= Number of look ahead trades that control up /down move
                    rolling_window= 15,
                    # Calculate threshold by means of moving average historical vol
                    thrshd_method=ThresholdMethod.arbitrary,
                    # Use the last 5 days for the above average. 
                    updown_thrshd_pct=1.)

TypeError: __init__() got an unexpected keyword argument 'updown_thrshd_pct'

In [49]:
labeller.label_training_data(data2) 


AttributeError: 'DataLabellingSimple' object has no attribute 'updown_thrshd_pct_'

In [20]:
labeller

In [ ]:
unique, counts= np.unique(x, return_counts=True)

In [60]:
print np.asarray((unique, counts)).T

[[-1.000e+00  4.779e+03]
 [ 1.000e+00  3.740e+03]
 [       nan  1.000e+00]
 [       nan  1.000e+00]
 [       nan  1.000e+00]
 [       nan  1.000e+00]]


In [61]:
from scipy.stats import itemfreq

In [69]:
itemfreq(x_1)

array([[-1.000e+00,  4.779e+03],
       [ 1.000e+00,  3.740e+03],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00]])

In [70]:
itemfreq(x_2)

array([[-1.000e+00,  4.468e+03],
       [ 1.000e+00,  4.041e+03],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00],
       [       nan,  1.000e+00]])

In [21]:
from hsmm_core.prediction_engines import *
from hsmm_core.data_utils import load_data, TradingHours
import sys
sys.path.append('/home/ak/Documents/Research/hsmm/')
from hsmm_core.data_utils import get_files_for_ticker, load_data
from hsmm_core.consts import ThresholdMethod, LabellingChoice

ticker = 'AAL'
n_hidden_states = 2

init_params = {
    "obs_model_params": {
                                'obs_model_name': 'ExpUniGauss',
                                'em_init_method': InitialisationMethod.cluster

    },
    "hidden_model_params": {
                                'no_hidden_states': n_hidden_states,
                                # 'pi':startprob,
                                # 'tpm': transmat
                                'em_init_method': InitialisationMethod.uniform
    },
    "update_tag": 'tpsml'
}

In [36]:

labelling_method_params = {
    'labelling_method': LabellingChoice.simple_ep_abs,
    'rolling_window': 10,
    'updown_threshold_pct': 5.,
    'threshold_method': ThresholdMethod.historical_vol_ma,
    'threshold_vol_window': 5,
    'updown_threshold_vol_pct': 10.,
}

In [37]:
prediction_params = {
    'labelling_method_params': labelling_method_params,
    'feature_generation': FeatureGeneration.one_model_to_one_fset,
}
start_dt = '20180416'
end_dt = '20180418'


In [39]:
trading_hours = TradingHours.only_mkt_hours

data_dic = load_data(ticker, start_date=start_dt, end_date=end_dt)




In [45]:
prediction_eng = hs_prediction_engine(hmm_init_params=init_params,
                                      prediction_innit_params=prediction_params,)


# features, _ = prediction_eng.train_model_data(ticker, data_dic, trading_hours, force_hmm_recalc=True)
# print features

TypeError: __init__() got an unexpected keyword argument 'updown_thrshd_pct'