In [2]:
import pandas as pd
import numpy as np
import sys
from hmm import hmm_calibration
from observation_models import Cartea, ExpGaussian

#sys.path.append("/home/Downloads")

rng = np.random.RandomState(1234)
no_hidden_states = 2
obs_model = Cartea(no_hidden_states)

the_hmm = hmm_calibration(obs_model, no_hidden_states)

data = pd.read_csv("/home/kman/Downloads/FIS_features_hmm_test__20150203.csv")

prices = data["TradePrice"]

data = data[["TradePrice", "TradeDuration"]]
data["TradeDuration"] *= 1e-3
data.columns = ['tau', 'price_change']
data.head() 

res = the_hmm.train_hmm(data, rng=rng, no_runs=10)
the_hmm.result_pretty_print(res, "**")


In run:  0
current log likelihood:  -111693846.242
Trasnition matrix for hidden:
[[ 0.58674743  0.41297468]
 [ 0.74075619  0.25896601]]
Initial probabilities for hidden:
[ 0.19597043  0.80402957]
 ******************************************
In run:  1
current log likelihood:  -111694003.919
Trasnition matrix for hidden:
[[ 0.45543381  0.54428831]
 [ 0.41648131  0.58324085]]
Initial probabilities for hidden:
[ 0.23984694  0.76015306]
 ******************************************
In run:  2
current log likelihood:  -111693369.71
Trasnition matrix for hidden:
[[ 0.65790003  0.34182211]
 [ 0.97308738  0.0266348 ]]
Initial probabilities for hidden:
[ 0.54906637  0.45093363]
 ******************************************
In run:  3
current log likelihood:  -111693378.314
Trasnition matrix for hidden:
[[ 0.70750202  0.2922202 ]
 [ 0.16977859  0.82994351]]
Initial probabilities for hidden:
[ 0.55707559  0.44292441]
 ******************************************
In run:  4
current log likelihood:  -1116