In [9]:
import numpy as np
import matplotlib.pyplot as plt

# Time horizon and steps
T = 100
dt = 1

# Initial portfolio
portfolio = np.array([-2., 40.])

# Simulate covariance matrix Sigma and Gamma
Sigma = np.array([[-0.2, 0.05], [0.05, 0.1]])
Gamma = np.array([[0.005, 0.002], [0.002, 0.003]])

# Bid-ask spread
spread_entry = np.array([0.005, 0.003])
spread_exit = np.array([0.007, 0.004])

# Liquidity constraint
MAX_TRADE_VALUE = 1000000

# Minimum trade size
MIN_TRADE_SIZE = 0.01

# Simulate prices
prices = np.zeros((T, 2))
prices[0] = [50000, 2000]
for t in range(1, T):
    prices[t] = prices[t - 1] * (1 + mu * dt + sigma * np.random.randn(2))

# Calculate the initial skew
def calculate_skew(portfolio, Sigma):
    return -np.dot(Gamma, portfolio)

# Calculate the trade size
def calculate_trade_size(skew, portfolio):
    return 0.05 * portfolio * np.sign(skew)

# Update the portfolio
def update_portfolio(portfolio, trade_size):
    portfolio += trade_size

# Initialize the lists to store the results
positions = [portfolio.copy()]
skews = []
pnl = [0]

# Simulate the market making process
for t in range(T):
    # Calculate the skew
    skew = calculate_skew(portfolio, Sigma)

    # Calculate the trade size
    trade_size = calculate_trade_size(skew, portfolio)

    # Update the portfolio
    update_portfolio(portfolio, trade_size)

    # Store the results
    positions.append(portfolio.copy())
    skews.append(skew.copy())
    pnl.append(pnl[-1] + (trade_size * (prices[t] - prices[t - 1])).sum())

# # Visualize the results
plt.figure(figsize=(12, 5))
plt.plot(positions[:, 0], label='BTC Position')
plt.plot(positions[:, 1], label='ETH Position')
plt.title('Portfolio Liquidation over Time')
plt.legend()
plt.show()

# plt.figure(figsize=(12, 5))
# plt.plot(skews[:, 0], label='BTC Skew')
# plt.plot(skews[:, 1], label='ETH Skew')
# plt.title('Market Making Skew over Time')
# plt.legend()
# plt.show()

# plt.figure(figsize=(12, 5))
# plt.plot(pnl)
# plt.title('PnL over Time')
# plt.show()


TypeError: list indices must be integers or slices, not tuple

<Figure size 864x360 with 0 Axes>

In [10]:
positions

[array([-2., 40.]),
 array([-1.9, 38. ]),
 array([-1.805, 36.1  ]),
 array([-1.71475, 34.295  ]),
 array([-1.6290125, 32.58025  ]),
 array([-1.54756187, 30.9512375 ]),
 array([-1.47018378, 29.40367562]),
 array([-1.39667459, 27.93349184]),
 array([-1.32684086, 26.53681725]),
 array([-1.26049882, 25.20997639]),
 array([-1.19747388, 23.94947757]),
 array([-1.13760018, 22.75200369]),
 array([-1.08072018, 21.61440351]),
 array([-1.02668417, 20.53368333]),
 array([-0.97534996, 19.50699916]),
 array([-0.92658246, 18.53164921]),
 array([-0.88025334, 17.60506675]),
 array([-0.83624067, 16.72481341]),
 array([-0.79442864, 15.88857274]),
 array([-0.75470721, 15.0941441 ]),
 array([-0.71697184, 14.3394369 ]),
 array([-0.68112325, 13.62246505]),
 array([-0.64706709, 12.9413418 ]),
 array([-0.61471374, 12.29427471]),
 array([-0.58397805, 11.67956097]),
 array([-0.55477915, 11.09558292]),
 array([-0.52704019, 10.54080378]),
 array([-0.50068818, 10.01376359]),
 array([-0.47565377,  9.51307541]),
 arr